apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: mariadb-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual