apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  namespace: test
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /data
          name: pvc-volume # volumes에서 정의된 pvc-volume과 일치
  volumes:
    - name: pvc-volume
      persistentVolumeClaim:
        claimName: mariadb-pvc