apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: test
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80         # Service 포트
      targetPort: 8080 # Pod에서 열려 있는 포트
      nodePort: 30001  # 외부에서 접근 가능한 고정 포트 (30000-32767)
  type: NodePort
